# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 407)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #41295a, stop:1 #2F0743);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aboutbutt = QtWidgets.QPushButton(self.centralwidget)
        self.aboutbutt.setGeometry(QtCore.QRect(490, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.aboutbutt.setFont(font)
        self.aboutbutt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutbutt.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"font-size:16px;\n"
"}\n"
"")
        self.aboutbutt.setObjectName("aboutbutt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 491, 141))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(98)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 45);\n"
"background-color: none;")
        self.label.setObjectName("label")
        self.startbutt = QtWidgets.QPushButton(self.centralwidget)
        self.startbutt.setGeometry(QtCore.QRect(90, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(20)
        self.startbutt.setFont(font)
        self.startbutt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startbutt.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"font-size:24px;\n"
"}\n"
"")
        self.startbutt.setObjectName("startbutt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 140, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(27)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_2.setObjectName("label_2")
        self.musicbutt = QtWidgets.QPushButton(self.centralwidget)
        self.musicbutt.setGeometry(QtCore.QRect(300, 350, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(15)
        self.musicbutt.setFont(font)
        self.musicbutt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.musicbutt.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"font-size:16px;\n"
"}\n"
"")
        self.musicbutt.setObjectName("musicbutt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PASSGEN"))
        self.aboutbutt.setText(_translate("MainWindow", "About Developer"))
        self.label.setText(_translate("MainWindow", "PASSGEN"))
        self.startbutt.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "The best password generator in the world"))
        self.musicbutt.setText(_translate("MainWindow", "music: on"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
